name: Build and push

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
    
      - name: debug
        run: ls
        
      - name: login
        id: image_build_push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
          
      - name: build push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hakobmkoyan771/appactions:latest
        
      - name: Get output
        run: |
          echo "${{ steps.image_build_push.outputs.imageinfo }}"
