name: Build and push

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
    
      - name: debug
        run: ls
        
      - name: build image
        id: image_build_push
        uses: ryanjfrizzell/action-bpd@master
        with:
          docker_registry_url: 'docker.io'
          docker_registry_owner: 'hakobmkoyan771'
          docker_repository: 'hakobmkoyan771'
          docker_image: 'actionsimage'
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          dockerfile: './Dockerfile'
        
      - name: Get output
        run: |
          echo "${{ steps.image_build_push.outputs.imageinfo }}"
