name: Build and push

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
    
      - name: debug
        run: ls
        
      - name: build image
        id: image_build_push
        uses: tegarimansyah/docker_build_push@master
        env:
            DOCKER_USER: ${{ secrets.docker_username }}
            PASSWORD: ${{ secrets.docker_password }}

            SEMVER: 0.1.0
            HOST: docker.com
            # if DEV is true then your image tag is as follow
            # 0.1.0-dev-c7bf9e21
            # where c7bf9e21 is your 8 char git hash
            # best for your staging server
            # else, the tag will be 0.1.0 ($SEMVER)
            DEV: true
        
      - name: Get output
        run: |
          echo "${{ steps.image_build_push.outputs.imageinfo }}"
